version: '3'

tasks:
    fixer:
        silent: true
        cmd: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix

    phpstan:
        silent: true
        cmd: tools/phpstan/vendor/bin/phpstan analyse src

    rector:
        silent: true
        cmd: tools/rector/vendor/bin/rector process
        
    fix:
        silent: true
        cmds:
            - task: rector
            - task: fixer
            - task: phpstan
            
    phpdoc:
        silent: true
        cmd: php phpdoc.phar -d src -t docs/php-doc
